# Generated by Django 5.0.6 on 2024-06-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
